/*
 jQuery JavaScript Library v2.1.0
 http://jquery.com/

 Includes Sizzle.js
 http://sizzlejs.com/

 Copyright 2005, 2014 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-01-23T21:10Z
 Sizzle CSS Selector Engine v1.10.16
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-01-13
*/
(function(q,la){"object"===typeof module&&"object"===typeof module.exports?module.exports=q.document?la(q,!0):function(q){if(!q.document)throw Error("jQuery requires a window with a document");return la(q)}:la(q)})("undefined"!==typeof window?window:this,function(q,la){function Ia(a){var b=a.length,d=c.type(a);return"function"===d||c.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===d||0===b||"number"===typeof b&&0<b&&b-1 in a}function Ja(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,
c,a)!==d});if(b.nodeType)return c.grep(a,function(a){return a===b!==d});if("string"===typeof b){if(Lb.test(b))return c.filter(b,a,d);b=c.filter(b,a)}return c.grep(a,function(a){return 0<=ua.call(b,a)!==d})}function Wa(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function Mb(a){var b=Xa[a]={};c.each(a.match(O)||[],function(a,c){b[c]=!0});return b}function va(){v.removeEventListener("DOMContentLoaded",va,!1);q.removeEventListener("load",va,!1);c.ready()}function X(){Object.defineProperty(this.cache=
{},0,{get:function(){return{}}});this.expando=c.expando+Math.random()}function Ya(a,b,d){if(void 0===d&&1===a.nodeType)if(d="data-"+b.replace(Nb,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:Ob.test(d)?c.parseJSON(d):d}catch(e){}w.set(a,b,d)}else d=void 0;return d}function da(){return!0}function Y(){return!1}function Za(){try{return v.activeElement}catch(a){}}function $a(a,b){return c.nodeName(a,"table")&&c.nodeName(11!==
b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function Pb(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function Qb(a){var b=Rb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function Ka(a,b){for(var d=0,c=a.length;d<c;d++)r.set(a[d],"globalEval",!b||r.get(b[d],"globalEval"))}function ab(a,b){var d,e;if(1===b.nodeType){if(r.hasData(a)){var f=r.access(a);var g=r.set(b,f);if(f=f.events)for(e in delete g.handle,
g.events={},f)for(g=0,d=f[e].length;g<d;g++)c.event.add(b,e,f[e][g])}w.hasData(a)&&(a=w.access(a),a=c.extend({},a),w.set(b,a))}}function x(a,b){var d=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&c.nodeName(a,b)?c.merge([a],d):d}function bb(a,b){a=c(b.createElement(a)).appendTo(b.body);b=q.getDefaultComputedStyle?q.getDefaultComputedStyle(a[0]).display:c.css(a[0],"display");a.detach();return b}function cb(a){var b=v,d=
db[a];d||(d=bb(a,b),"none"!==d&&d||(wa=(wa||c("<iframe frameborder='0' width='0' height='0'/>")).appendTo(b.documentElement),b=wa[0].contentDocument,b.write(),b.close(),d=bb(a,b),wa.detach()),db[a]=d);return d}function ma(a,b,d){var e,f=a.style;(d=d||xa(a))&&(e=d.getPropertyValue(b)||d[b]);if(d&&(""!==e||c.contains(a.ownerDocument,a)||(e=c.style(a,b)),La.test(e)&&eb.test(b))){a=f.width;b=f.minWidth;var g=f.maxWidth;f.minWidth=f.maxWidth=f.width=e;e=d.width;f.width=a;f.minWidth=b;f.maxWidth=g}return void 0!==
e?e+"":e}function fb(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function gb(a,b){if(b in a)return b;for(var d=b[0].toUpperCase()+b.slice(1),c=b,f=hb.length;f--;)if(b=hb[f]+d,b in a)return b;return c}function ib(a,b,d){return(a=Sb.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function jb(a,b,d,e,f){b=d===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+Z[b],!0,f)),e?("content"===d&&(g-=c.css(a,"padding"+
Z[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+Z[b]+"Width",!0,f))):(g+=c.css(a,"padding"+Z[b],!0,f),"padding"!==d&&(g+=c.css(a,"border"+Z[b]+"Width",!0,f)));return g}function kb(a,b,d){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,g=xa(a),h="border-box"===c.css(a,"boxSizing",!1,g);if(0>=f||null==f){f=ma(a,b,g);if(0>f||null==f)f=a.style[b];if(La.test(f))return f;e=h&&(t.boxSizingReliable()||f===a.style[b]);f=parseFloat(f)||0}return f+jb(a,b,d||(h?"border":"content"),e,g)+"px"}function lb(a,
b){for(var d,e,f,g=[],h=0,k=a.length;h<k;h++)e=a[h],e.style&&(g[h]=r.get(e,"olddisplay"),d=e.style.display,b?(g[h]||"none"!==d||(e.style.display=""),""===e.style.display&&na(e)&&(g[h]=r.access(e,"olddisplay",cb(e.nodeName)))):g[h]||(f=na(e),(d&&"none"!==d||!f)&&r.set(e,"olddisplay",f?d:c.css(e,"display"))));for(h=0;h<k;h++)e=a[h],!e.style||b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[h]||"":"none");return a}function C(a,b,d,c,f){return new C.prototype.init(a,b,d,c,f)}function mb(){setTimeout(function(){aa=
void 0});return aa=c.now()}function ea(a,b){var d=0,c={height:a};for(b=b?1:0;4>d;d+=2-b){var f=Z[d];c["margin"+f]=c["padding"+f]=a}b&&(c.opacity=c.width=a);return c}function nb(a,b,d){for(var c,f=(oa[b]||[]).concat(oa["*"]),g=0,h=f.length;g<h;g++)if(c=f[g].call(d,b,a))return c}function Tb(a,b){var d,e;for(d in a){var f=c.camelCase(d);var g=b[f];var h=a[d];c.isArray(h)&&(g=h[1],h=a[d]=h[0]);d!==f&&(a[f]=h,delete a[d]);if((e=c.cssHooks[f])&&"expand"in e)for(d in h=e.expand(h),delete a[f],h)d in a||
(a[d]=h[d],b[d]=g);else b[f]=g}}function ob(a,b,d){var e,f=0,g=pa.length,h=c.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;var b=aa||mb();b=Math.max(0,l.startTime+l.duration-b);for(var d=1-(b/l.duration||0),c=0,f=l.tweens.length;c<f;c++)l.tweens[c].run(d);h.notifyWith(a,[l,d,b]);if(1>d&&f)return b;h.resolveWith(a,[l]);return!1},l=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:aa||mb(),duration:d.duration,
tweens:[],createTween:function(b,d){b=c.Tween(a,l.opts,b,d,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(b);return b},stop:function(b){var d=0,c=b?l.tweens.length:0;if(e)return this;for(e=!0;d<c;d++)l.tweens[d].run(1);b?h.resolveWith(a,[l,b]):h.rejectWith(a,[l,b]);return this}});d=l.props;for(Tb(d,l.opts.specialEasing);f<g;f++)if(b=pa[f].call(l,a,d,l.opts))return b;c.map(d,nb,l);c.isFunction(l.opts.start)&&l.opts.start.call(a,l);c.fx.timer(c.extend(k,{elem:a,anim:l,queue:l.opts.queue}));return l.progress(l.opts.progress).done(l.opts.done,
l.opts.complete).fail(l.opts.fail).always(l.opts.always)}function pb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e=0,f=b.toLowerCase().match(O)||[];if(c.isFunction(d))for(;b=f[e++];)"+"===b[0]?(b=b.slice(1)||"*",(a[b]=a[b]||[]).unshift(d)):(a[b]=a[b]||[]).push(d)}}function qb(a,b,d,e){function f(k){var l;g[k]=!0;c.each(a[k]||[],function(a,c){a=c(b,d,e);if("string"===typeof a&&!h&&!g[a])return b.dataTypes.unshift(a),f(a),!1;if(h)return!(l=a)});return l}var g={},h=a===Ma;return f(b.dataTypes[0])||
!g["*"]&&f("*")}function Na(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)void 0!==b[d]&&((f[d]?a:e||(e={}))[d]=b[d]);e&&c.extend(!0,a,e);return a}function Oa(a,b,d,e){var f;if(c.isArray(b))c.each(b,function(b,c){d||Ub.test(a)?e(a,c):Oa(a+"["+("object"===typeof c?b:"")+"]",c,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)Oa(a+"["+f+"]",b[f],d,e)}function rb(a){return c.isWindow(a)?a:9===a.nodeType&&a.defaultView}var S=[],N=S.slice,sb=S.concat,Pa=S.push,ua=S.indexOf,Ca={},
Vb=Ca.toString,Qa=Ca.hasOwnProperty,Wb="".trim,t={},v=q.document,c=function(a,b){return new c.fn.init(a,b)},Xb=/^-ms-/,Yb=/-([\da-z])/gi,Zb=function(a,b){return b.toUpperCase()};c.fn=c.prototype={jquery:"2.1.0",constructor:c,selector:"",length:0,toArray:function(){return N.call(this)},get:function(a){return null!=a?0>a?this[a+this.length]:this[a]:N.call(this)},pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;return a},each:function(a,b){return c.each(this,
a,b)},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},slice:function(){return this.pushStack(N.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor(null)},push:Pa,sort:S.sort,splice:S.splice};c.extend=c.fn.extend=function(){var a,b,d,e=arguments[0]||{},f=1,g=arguments.length,
h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},f++);"object"===typeof e||c.isFunction(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var k=e[b];var l=a[b];e!==l&&(h&&l&&(c.isPlainObject(l)||(d=c.isArray(l)))?(d?(d=!1,k=k&&c.isArray(k)?k:[]):k=k&&c.isPlainObject(k)?k:{},e[b]=c.extend(h,k,l)):void 0!==l&&(e[b]=l))}return e};c.extend({expando:"jQuery"+("2.1.0"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===
c.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){return 0<=a-parseFloat(a)},isPlainObject:function(a){if("object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!Qa.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?Ca[Vb.call(a)]||"object":typeof a},
globalEval:function(a){var b=q.eval;if(a=c.trim(a))1===a.indexOf("use strict")?(b=v.createElement("script"),b.text=a,v.head.appendChild(b).parentNode.removeChild(b)):b(a)},camelCase:function(a){return a.replace(Xb,"ms-").replace(Yb,Zb)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,d){var c=0,f=a.length;var g=Ia(a);if(d)if(g)for(;c<f&&(g=b.apply(a[c],d),!1!==g);c++);else for(c in a){if(g=b.apply(a[c],d),!1===g)break}else if(g)for(;c<f&&(g=
b.call(a[c],c,a[c]),!1!==g);c++);else for(c in a)if(g=b.call(a[c],c,a[c]),!1===g)break;return a},trim:function(a){return null==a?"":Wb.call(a)},makeArray:function(a,b){b=b||[];null!=a&&(Ia(Object(a))?c.merge(b,"string"===typeof a?[a]:a):Pa.call(b,a));return b},inArray:function(a,b,d){return null==b?-1:ua.call(b,a,d)},merge:function(a,b){for(var d=+b.length,c=0,f=a.length;c<d;c++)a[f++]=b[c];a.length=f;return a},grep:function(a,b,d){for(var c=[],f=0,g=a.length,h=!d;f<g;f++)d=!b(a[f],f),d!==h&&c.push(a[f]);
return c},map:function(a,b,d){var c=0,f=a.length,g=[];if(Ia(a))for(;c<f;c++){var h=b(a[c],c,d);null!=h&&g.push(h)}else for(c in a)h=b(a[c],c,d),null!=h&&g.push(h);return sb.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var d=a[b];b=a;a=d}if(c.isFunction(a)){var e=N.call(arguments,2);d=function(){return a.apply(b||this,e.concat(N.call(arguments)))};d.guid=a.guid=a.guid||c.guid++;return d}},now:Date.now,support:t});c.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),
function(a,b){Ca["[object "+b+"]"]=b.toLowerCase()});var R=function(a){function b(a,b,c,d){var e,f,g,u;(b?b.ownerDocument||b:I)!==J&&qa(b);b=b||J;c=c||[];if(!a||"string"!==typeof a)return c;if(1!==(u=b.nodeType)&&9!==u)return[];if(T&&!d){if(e=va.exec(a))if(g=e[1])if(9===u)if((f=b.getElementById(g))&&f.parentNode){if(f.id===g)return c.push(f),c}else return c;else{if(b.ownerDocument&&(f=b.ownerDocument.getElementById(g))&&Aa(b,f)&&f.id===g)return c.push(f),c}else{if(e[2])return fa.apply(c,b.getElementsByTagName(a)),
c;if((g=e[3])&&D.getElementsByClassName&&b.getElementsByClassName)return fa.apply(c,b.getElementsByClassName(g)),c}if(D.qsa&&(!Q||!Q.test(a))){f=e=y;g=b;var h=9===u&&a;if(1===u&&"object"!==b.nodeName.toLowerCase()){u=ba(a);(e=b.getAttribute("id"))?f=e.replace(wa,"\\$&"):b.setAttribute("id",f);f="[id='"+f+"'] ";for(g=u.length;g--;)u[g]=f+r(u[g]);g=da.test(a)&&p(b.parentNode)||b;h=u.join(",")}if(h)try{return fa.apply(c,g.querySelectorAll(h)),c}catch(Dc){}finally{e||b.removeAttribute("id")}}}var z;a:{a=
a.replace(R,"$1");f=ba(a);if(!d&&1===f.length){e=f[0]=f[0].slice(0);if(2<e.length&&"ID"===(z=e[0]).type&&D.getById&&9===b.nodeType&&T&&B.relative[e[1].type]){b=(B.find.ID(z.matches[0].replace(ha,ia),b)||[])[0];if(!b){z=c;break a}a=a.slice(e.shift().value.length)}for(u=V.needsContext.test(a)?0:e.length;u--;){z=e[u];if(B.relative[g=z.type])break;if(g=B.find[g])if(d=g(z.matches[0].replace(ha,ia),da.test(e[0].type)&&p(b.parentNode)||b)){e.splice(u,1);a=d.length&&r(e);if(!a){fa.apply(c,d);z=c;break a}break}}}pa(a,
f)(d,b,!T,c,da.test(a)&&p(b.parentNode)||b);z=c}return z}function c(){function a(c,d){b.push(c+" ")>B.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[y]=!0;return a}function f(a){var b=J.createElement("div");try{return!!a(b)}catch(z){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){var c=a.split("|");for(a=a.length;a--;)B.attrHandle[c[a]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||-2147483648)-
(~a.sourceIndex||-2147483648);if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function m(a){return e(function(b){b=+b;return e(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function p(a){return a&&"undefined"!==typeof a.getElementsByTagName&&
a}function n(){}function ba(a,c){var d,e,f,g,u;if(g=P[a+" "])return c?0:g.slice(0);g=a;var h=[];for(u=B.preFilter;g;){if(!k||(d=ka.exec(g)))d&&(g=g.slice(d[0].length)||g),h.push(e=[]);var k=!1;if(d=la.exec(g))k=d.shift(),e.push({value:k,type:d[0].replace(R," ")}),g=g.slice(k.length);for(f in B.filter)!(d=V[f].exec(g))||u[f]&&!(d=u[f](d))||(k=d.shift(),e.push({value:k,type:f,matches:d}),g=g.slice(k.length));if(!k)break}return c?g.length:g?b.error(a):P(a,h).slice(0)}function r(a){for(var b=0,c=a.length,
d="";b<c;b++)d+=a[b].value;return d}function q(a,b,c){var d=b.dir,e=c&&"parentNode"===d,f=C++;return b.first?function(b,c,f){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,f)}:function(b,c,g){var u,h=[K,f];if(g)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,g))return!0}else for(;b=b[d];)if(1===b.nodeType||e){var z=b[y]||(b[y]={});if((u=z[d])&&u[0]===K&&u[1]===f)return h[2]=u[2];z[d]=h;if(h[2]=a(b,c,g))return!0}}}function v(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;
return!0}:a[0]}function t(a,b,c,d,e){for(var f,g=[],u=0,h=a.length,z=null!=b;u<h;u++)if(f=a[u])if(!c||c(f,d,e))g.push(f),z&&b.push(u);return g}function w(a,c,d,f,g,h){f&&!f[y]&&(f=w(f));g&&!g[y]&&(g=w(g,h));return e(function(e,u,h,z){var k,l=[],m=[],H=u.length,F;if(!(F=e)){F=c||"*";for(var n=h.nodeType?[h]:h,p=[],ya=0,ba=n.length;ya<ba;ya++)b(F,n[ya],p);F=p}F=!a||!e&&c?F:t(F,l,a,h,z);n=d?g||(e?a:H||f)?[]:u:F;d&&d(F,n,h,z);if(f){var r=t(n,m);f(r,[],h,z);for(h=r.length;h--;)if(k=r[h])n[m[h]]=!(F[m[h]]=
k)}if(e){if(g||a){if(g){r=[];for(h=n.length;h--;)(k=n[h])&&r.push(F[h]=k);g(null,n=[],r,z)}for(h=n.length;h--;)(k=n[h])&&-1<(r=g?ra.call(e,k):l[h])&&(e[r]=!(u[r]=k))}}else n=t(n===u?n.splice(H,n.length):n),g?g(null,u,n,z):fa.apply(u,n)})}function x(a){var b,c,d=a.length,e=B.relative[a[0].type];var f=e||B.relative[" "];for(var g=e?1:0,h=q(function(a){return a===b},f,!0),u=q(function(a){return-1<ra.call(b,a)},f,!0),k=[function(a,c,d){return!e&&(d||c!==G)||((b=c).nodeType?h(a,c,d):u(a,c,d))}];g<d;g++)if(f=
B.relative[a[g].type])k=[q(v(k),f)];else{f=B.filter[a[g].type].apply(null,a[g].matches);if(f[y]){for(c=++g;c<d&&!B.relative[a[c].type];c++);return w(1<g&&v(k),1<g&&r(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(R,"$1"),f,g<c&&x(a.slice(g,c)),c<d&&x(a=a.slice(c)),c<d&&r(a))}k.push(f)}return v(k)}function A(a,c){var d=0<c.length,f=0<a.length,g=function(e,g,h,u,k){var z,l,m,H=0,F="0",n=e&&[],p=[],r=G,ya=e||f&&B.find.TAG("*",k),ba=K+=null==r?1:Math.random()||.1,q=ya.length;for(k&&
(G=g!==J&&g);F!==q&&null!=(z=ya[F]);F++){if(f&&z){for(l=0;m=a[l++];)if(m(z,g,h)){u.push(z);break}k&&(K=ba)}d&&((z=!m&&z)&&H--,e&&n.push(z))}H+=F;if(d&&F!==H){for(l=0;m=c[l++];)m(n,p,g,h);if(e){if(0<H)for(;F--;)n[F]||p[F]||(p[F]=X.call(u));p=t(p)}fa.apply(u,p);k&&!e&&0<p.length&&1<H+c.length&&b.uniqueSort(u)}k&&(K=ba,G=r);return n};return d?e(g):g}var L,G,M,za,J,ca,T,Q,sa,Da,Aa,y="sizzle"+-new Date,I=a.document,K=0,C=0,E=c(),P=c(),O=c(),N=function(a,b){a===b&&(za=!0);return 0},U={}.hasOwnProperty,
ja=[],X=ja.pop,Z=ja.push,fa=ja.push,W=ja.slice,ra=ja.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},Y="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),aa="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+Y+")|)|)[\\x20\\t\\r\\n\\f]*\\]",S=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+aa.replace(3,8)+
")*)|.*)\\)|)",R=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,ka=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,la=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ma=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,na=new RegExp(S),oa=new RegExp("^"+Y+"$"),V={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:new RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:new RegExp("^"+aa),PSEUDO:new RegExp("^"+S),CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,
bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},ta=/^(?:input|select|textarea|button)$/i,ua=/^h\d$/i,Ba=/^[^{]+\{\s*\[native \w/,va=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,wa=/'|\\/g,ha=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,ia=function(a,b,c){a="0x"+b-65536;
return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{fa.apply(ja=W.call(I.childNodes),I.childNodes),ja[I.childNodes.length].nodeType}catch(u){fa={apply:ja.length?function(a,b){Z.apply(a,W.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var D=b.support={};var xa=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var qa=b.setDocument=function(a){var b=a?a.ownerDocument||a:I;a=b.defaultView;
if(b===J||9!==b.nodeType||!b.documentElement)return J;J=b;ca=b.documentElement;T=!xa(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){qa()},!1):a.attachEvent&&a.attachEvent("onunload",function(){qa()}));D.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});D.getElementsByTagName=f(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});D.getElementsByClassName=Ba.test(b.getElementsByClassName)&&f(function(a){a.innerHTML=
"<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});D.getById=f(function(a){ca.appendChild(a).id=y;return!b.getElementsByName||!b.getElementsByName(y).length});D.getById?(B.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&T)return(a=b.getElementById(a))&&a.parentNode?[a]:[]},B.filter.ID=function(a){var b=a.replace(ha,ia);return function(a){return a.getAttribute("id")===b}}):(delete B.find.ID,B.filter.ID=function(a){var b=
a.replace(ha,ia);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}});B.find.TAG=D.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var c=[],d=0;b=b.getElementsByTagName(a);if("*"===a){for(;a=b[d++];)1===a.nodeType&&c.push(a);return c}return b};B.find.CLASS=D.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&T)return b.getElementsByClassName(a)};
sa=[];Q=[];if(D.qsa=Ba.test(b.querySelectorAll))f(function(a){a.innerHTML="<select t=''><option selected=''></option></select>";a.querySelectorAll("[t^='']").length&&Q.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||Q.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||Q.push(":checked")}),f(function(a){var c=
b.createElement("input");c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&Q.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||Q.push(":enabled",":disabled");a.querySelectorAll("*,:x");Q.push(",.*:")});(D.matchesSelector=Ba.test(Da=ca.webkitMatchesSelector||ca.mozMatchesSelector||ca.oMatchesSelector||ca.msMatchesSelector))&&f(function(a){D.disconnectedMatch=Da.call(a,"div");Da.call(a,"[s!='']:x");sa.push("!=",
S)});Q=Q.length&&new RegExp(Q.join("|"));sa=sa.length&&new RegExp(sa.join("|"));Aa=(a=Ba.test(ca.compareDocumentPosition))||Ba.test(ca.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a;b=b&&b.parentNode;return a===b||!!(b&&1===b.nodeType&&(c.contains?c.contains(b):a.compareDocumentPosition&&a.compareDocumentPosition(b)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};N=a?function(a,c){if(a===c)return za=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;
if(d)return d;d=(a.ownerDocument||a)===(c.ownerDocument||c)?a.compareDocumentPosition(c):1;return d&1||!D.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===I&&Aa(I,a)?-1:c===b||c.ownerDocument===I&&Aa(I,c)?1:M?ra.call(M,a)-ra.call(M,c):0:d&4?-1:1}:function(a,c){if(a===c)return za=!0,0;var d=0,e=a.parentNode,f=c.parentNode,g=[a],u=[c];if(!e||!f)return a===b?-1:c===b?1:e?-1:f?1:M?ra.call(M,a)-ra.call(M,c):0;if(e===f)return h(a,c);for(;a=a.parentNode;)g.unshift(a);for(a=c;a=a.parentNode;)u.unshift(a);
for(;g[d]===u[d];)d++;return d?h(g[d],u[d]):g[d]===I?-1:u[d]===I?1:0};return b};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==J&&qa(a);c=c.replace(ma,"='$1']");if(!(!D.matchesSelector||!T||sa&&sa.test(c)||Q&&Q.test(c)))try{var d=Da.call(a,c);if(d||D.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(F){}return 0<b(c,J,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==J&&qa(a);return Aa(a,b)};b.attr=function(a,
b){(a.ownerDocument||a)!==J&&qa(a);var c=B.attrHandle[b.toLowerCase()];c=c&&U.call(B.attrHandle,b.toLowerCase())?c(a,b,!T):void 0;return void 0!==c?c:D.attributes||!T?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;za=!D.detectDuplicates;M=!D.sortStable&&a.slice(0);a.sort(N);if(za){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}M=null;
return a};var ea=b.getText=function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=ea(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=ea(a)}else if(3===d||4===d)return a.nodeValue;return b};var B=b.selectors={cacheLength:50,createPseudo:e,match:V,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=
a[1].replace(ha,ia);a[3]=(a[4]||a[5]||"").replace(ha,ia);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(V.CHILD.test(a[0]))return null;a[3]&&void 0!==a[4]?a[2]=a[4]:c&&na.test(c)&&(b=ba(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(ha,ia).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=E[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),E(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,
a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,k){var l;c=f!==g?"nextSibling":"previousSibling";var m=b.parentNode,u=h&&b.nodeName.toLowerCase();
k=!k&&!h;if(m){if(f){for(;c;){for(l=b;l=l[c];)if(h?l.nodeName.toLowerCase()===u:1===l.nodeType)return!1;var n=c="only"===a&&!n&&"nextSibling"}return!0}n=[g?m.firstChild:m.lastChild];if(g&&k){k=m[y]||(m[y]={});var p=k[a]||[];var z=p[0]===K&&p[1];var H=p[0]===K&&p[2];for(l=z&&m.childNodes[z];l=++z&&l&&l[c]||(H=z=0)||n.pop();)if(1===l.nodeType&&++H&&l===b){k[a]=[K,z,H];break}}else if(k&&(p=(b[y]||(b[y]={}))[a])&&p[0]===K)H=p[1];else for(;(l=++z&&l&&l[c]||(H=z=0)||n.pop())&&((h?l.nodeName.toLowerCase()!==
u:1!==l.nodeType)||!++H||(k&&((l[y]||(l[y]={}))[a]=[K,H]),l!==b)););H-=e;return H===d||0===H%d&&0<=H/d}}},PSEUDO:function(a,c){var d=B.pseudos[a]||B.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(d[y])return d(c);if(1<d.length){var f=[a,a,"",c];return B.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var e,f=d(a,c),g=f.length;g--;)e=ra.call(a,f[g]),a[e]=!(b[e]=f[g])}):function(a){return d(a,0,f)}}return d}},pseudos:{not:e(function(a){var b=[],c=[],d=pa(a.replace(R,
"$1"));return d[y]?e(function(a,b,c,e){e=d(a,null,e,[]);for(var f=a.length;f--;)if(c=e[f])a[f]=!(b[f]=c)}):function(a,e,f){b[0]=a;d(b,null,f,c);return!c.pop()}}),has:e(function(a){return function(c){return 0<b(a,c).length}}),contains:e(function(a){return function(b){return-1<(b.textContent||b.innerText||ea(b)).indexOf(a)}}),lang:e(function(a){oa.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(ha,ia).toLowerCase();return function(b){var c;do if(c=T?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=
c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===ca},focus:function(a){return a===J.activeElement&&(!J.hasFocus||J.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&
!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!B.pseudos.empty(a)},header:function(a){return ua.test(a.nodeName)},input:function(a){return ta.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===
a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:m(function(){return[0]}),last:m(function(a,b){return[b-1]}),eq:m(function(a,b,c){return[0>c?c+b:c]}),even:m(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:m(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:m(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:m(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};B.pseudos.nth=B.pseudos.eq;for(L in{radio:!0,checkbox:!0,file:!0,password:!0,
image:!0})B.pseudos[L]=k(L);for(L in{submit:!0,reset:!0})B.pseudos[L]=l(L);n.prototype=B.filters=B.pseudos;B.setFilters=new n;var pa=b.compile=function(a,b){var c,d=[],e=[],f=O[a+" "];if(!f){b||(b=ba(a));for(c=b.length;c--;)f=x(b[c]),f[y]?d.push(f):e.push(f);f=O(a,A(e,d))}return f};D.sortStable=y.split("").sort(N).join("")===y;D.detectDuplicates=!!za;qa();D.sortDetached=f(function(a){return a.compareDocumentPosition(J.createElement("div"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===
a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});D.attributes&&f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(q);c.find=R;c.expr=R.selectors;c.expr[":"]=c.expr.pseudos;c.unique=R.uniqueSort;c.text=R.getText;c.isXMLDoc=R.isXML;c.contains=R.contains;var tb=c.expr.match.needsContext,ub=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Lb=/^.[^:#\[\.,]*$/;c.filter=function(a,b,d){var e=b[0];d&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?c.find.matchesSelector(e,a)?[e]:[]:c.find.matches(a,c.grep(b,
function(a){return 1===a.nodeType}))};c.fn.extend({find:function(a){var b,d=this.length,e=[],f=this;if("string"!==typeof a)return this.pushStack(c(a).filter(function(){for(b=0;b<d;b++)if(c.contains(f[b],this))return!0}));for(b=0;b<d;b++)c.find(a,f[b],e);e=this.pushStack(1<d?c.unique(e):e);e.selector=this.selector?this.selector+" "+a:a;return e},filter:function(a){return this.pushStack(Ja(this,a||[],!1))},not:function(a){return this.pushStack(Ja(this,a||[],!0))},is:function(a){return!!Ja(this,"string"===
typeof a&&tb.test(a)?c(a):a||[],!1).length}});var bc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/;(c.fn.init=function(a,b){if(!a)return this;if("string"===typeof a){var d="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:bc.exec(a);if(!d||!d[1]&&b)return!b||b.jquery?(b||Ra).find(a):this.constructor(b).find(a);if(d[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(d[1],b&&b.nodeType?b.ownerDocument||b:v,!0)),ub.test(d[1])&&c.isPlainObject(b))for(d in b)if(c.isFunction(this[d]))this[d](b[d]);
else this.attr(d,b[d])}else(b=v.getElementById(d[2]))&&b.parentNode&&(this.length=1,this[0]=b),this.context=v,this.selector=a;return this}if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if(c.isFunction(a))return"undefined"!==typeof Ra.ready?Ra.ready(a):a(c);void 0!==a.selector&&(this.selector=a.selector,this.context=a.context);return c.makeArray(a,this)}).prototype=c.fn;var Ra=c(v);var cc=/^(?:parents|prev(?:Until|All))/,dc={children:!0,contents:!0,next:!0,prev:!0};c.extend({dir:function(a,
b,d){for(var e=[],f=void 0!==d;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&c(a).is(d))break;e.push(a)}return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});c.fn.extend({has:function(a){var b=c(a,this),d=b.length;return this.filter(function(){for(var a=0;a<d;a++)if(c.contains(this,b[a]))return!0})},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=tb.test(a)||"string"!==typeof a?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d!==
b;d=d.parentNode)if(11>d.nodeType&&(h?-1<h.index(d):1===d.nodeType&&c.find.matchesSelector(d,a))){g.push(d);break}return this.pushStack(1<g.length?c.unique(g):g)},index:function(a){return a?"string"===typeof a?ua.call(c(a),this[0]):ua.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(c.unique(c.merge(this.get(),c(a,b))))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.each({parent:function(a){return(a=
a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return c.dir(a,"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return Wa(a,"nextSibling")},prev:function(a){return Wa(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||
{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},contents:function(a){return a.contentDocument||c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);"Until"!==a.slice(-5)&&(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));1<this.length&&(dc[a]||c.unique(f),cc.test(a)&&f.reverse());return this.pushStack(f)}});var O=/\S+/g,Xa={};c.Callbacks=function(a){a="string"===typeof a?Xa[a]||Mb(a):c.extend({},a);var b,d,e,f,g,h,k=[],l=!a.once&&[],m=function(c){b=
a.memory&&c;d=!0;h=f||0;f=0;g=k.length;for(e=!0;k&&h<g;h++)if(!1===k[h].apply(c[0],c[1])&&a.stopOnFalse){b=!1;break}e=!1;k&&(l?l.length&&m(l.shift()):b?k=[]:p.disable())},p={add:function(){if(k){var d=k.length;(function $b(b){c.each(b,function(b,d){b=c.type(d);"function"===b?a.unique&&p.has(d)||k.push(d):d&&d.length&&"string"!==b&&$b(d)})})(arguments);e?g=k.length:b&&(f=d,m(b))}return this},remove:function(){k&&c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,k,d));)k.splice(d,1),e&&(d<=
g&&g--,d<=h&&h--)});return this},has:function(a){return a?-1<c.inArray(a,k):!(!k||!k.length)},empty:function(){k=[];g=0;return this},disable:function(){k=l=b=void 0;return this},disabled:function(){return!k},lock:function(){l=void 0;b||p.disable();return this},locked:function(){return!l},fireWith:function(a,b){!k||d&&!l||(b=b||[],b=[a,b.slice?b.slice():b],e?l.push(b):m(b));return this},fire:function(){p.fireWith(this,arguments);return this},fired:function(){return!!d}};return p};c.extend({Deferred:function(a){var b=
[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var a=arguments;return c.Deferred(function(d){c.each(b,function(b,g){var h=c.isFunction(a[b])&&a[b];f[g[1]](function(){var a=h&&h.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().done(d.resolve).fail(d.reject).progress(d.notify);
else d[g[0]+"With"](this===e?d.promise():this,h?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=a?c.extend(a,e):e}},f={};e.pipe=e.then;c.each(b,function(a,c){var g=c[2],h=c[3];e[c[1]]=g.add;h&&g.add(function(){d=h},b[a^1][2].disable,b[2][2].lock);f[c[0]]=function(){f[c[0]+"With"](this===f?e:this,arguments);return this};f[c[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,d=N.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?
e:0,g=1===f?a:c.Deferred(),h=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?N.call(arguments):d;c===l?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},k;if(1<e){var l=Array(e);var m=Array(e);for(k=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,k,d)).fail(g.reject).progress(h(b,m,l)):--f}f||g.resolveWith(k,d);return g.promise()}});var Ea;c.fn.ready=function(a){c.ready.promise().done(a);return this};c.extend({isReady:!1,readyWait:1,holdReady:function(a){a?
c.readyWait++:c.ready(!0)},ready:function(a){(!0===a?--c.readyWait:c.isReady)||(c.isReady=!0,!0!==a&&0<--c.readyWait||(Ea.resolveWith(v,[c]),c.fn.trigger&&c(v).trigger("ready").off("ready")))}});c.ready.promise=function(a){Ea||(Ea=c.Deferred(),"complete"===v.readyState?setTimeout(c.ready):(v.addEventListener("DOMContentLoaded",va,!1),q.addEventListener("load",va,!1)));return Ea.promise(a)};c.ready.promise();var U=c.access=function(a,b,d,e,f,g,h){var k=0,l=a.length,m=null==d;if("object"===c.type(d))for(k in f=
!0,d)c.access(a,b,k,d[k],!0,g,h);else if(void 0!==e&&(f=!0,c.isFunction(e)||(h=!0),m&&(h?(b.call(a,e),b=null):(m=b,b=function(a,b,d){return m.call(c(a),d)})),b))for(;k<l;k++)b(a[k],d,h?e:e.call(a[k],k,b(a[k],d)));return f?a:m?b.call(a):l?b(a[0],d):g};c.acceptData=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};X.uid=1;X.accepts=c.acceptData;X.prototype={key:function(a){if(!X.accepts(a))return 0;var b={},d=a[this.expando];if(!d){d=X.uid++;try{b[this.expando]={value:d},Object.defineProperties(a,
b)}catch(e){b[this.expando]=d,c.extend(a,b)}}this.cache[d]||(this.cache[d]={});return d},set:function(a,b,d){var e;a=this.key(a);var f=this.cache[a];if("string"===typeof b)f[b]=d;else if(c.isEmptyObject(f))c.extend(this.cache[a],b);else for(e in b)f[e]=b[e];return f},get:function(a,b){a=this.cache[this.key(a)];return void 0===b?a:a[b]},access:function(a,b,d){if(void 0===b||b&&"string"===typeof b&&void 0===d)return d=this.get(a,b),void 0!==d?d:this.get(a,c.camelCase(b));this.set(a,b,d);return void 0!==
d?d:b},remove:function(a,b){var d=this.key(a);a=this.cache[d];if(void 0===b)this.cache[d]={};else for(c.isArray(b)?d=b.concat(b.map(c.camelCase)):(d=c.camelCase(b),d=b in a?[b,d]:d in a?[d]:d.match(O)||[]),b=d.length;b--;)delete a[d[b]]},hasData:function(a){return!c.isEmptyObject(this.cache[a[this.expando]]||{})},discard:function(a){a[this.expando]&&delete this.cache[a[this.expando]]}};var r=new X,w=new X,Ob=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Nb=/([A-Z])/g;c.extend({hasData:function(a){return w.hasData(a)||
r.hasData(a)},data:function(a,b,c){return w.access(a,b,c)},removeData:function(a,b){w.remove(a,b)},_data:function(a,b,c){return r.access(a,b,c)},_removeData:function(a,b){r.remove(a,b)}});c.fn.extend({data:function(a,b){var d,e=this[0],f=e&&e.attributes;if(void 0===a){if(this.length){var g=w.get(e);if(1===e.nodeType&&!r.get(e,"hasDataAttrs")){for(d=f.length;d--;){var h=f[d].name;0===h.indexOf("data-")&&(h=c.camelCase(h.slice(5)),Ya(e,h,g[h]))}r.set(e,"hasDataAttrs",!0)}}return g}return"object"===
typeof a?this.each(function(){w.set(this,a)}):U(this,function(b){var d=c.camelCase(a);if(e&&void 0===b){var f=w.get(e,a);if(void 0!==f)return f;f=w.get(e,d);if(void 0!==f)return f;f=Ya(e,d,void 0);if(void 0!==f)return f}else this.each(function(){var c=w.get(this,d);w.set(this,d,b);-1!==a.indexOf("-")&&void 0!==c&&w.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){w.remove(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";
var e=r.get(a,b);d&&(!e||c.isArray(d)?e=r.access(a,b,c.makeArray(d)):e.push(d));return e||[]}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return r.get(a,d)||r.access(a,d,{empty:c.Callbacks("once memory").add(function(){r.remove(a,[b+"queue",d])})})}});
c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):void 0===b?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==
typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(d=r.get(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(k));k();return f.promise(b)}});var Fa=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,Z=["Top","Right","Bottom","Left"],na=function(a,b){a=b||a;return"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)},vb=/^(?:checkbox|radio)$/i;(function(){var a=v.createDocumentFragment().appendChild(v.createElement("div"));a.innerHTML="<input type='radio' checked='checked' name='t'/>";t.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;
a.innerHTML="<textarea>x</textarea>";t.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();t.focusinBubbles="onfocusin"in q;var ec=/^key/,fc=/^(?:mouse|contextmenu)|click/,wb=/^(?:focusinfocus|focusoutblur)$/,xb=/^([^.]*)(?:\.(.+)|)$/;c.event={global:{},add:function(a,b,d,e,f){var g,h,k,l,m;if(k=r.get(a)){if(d.handler){var p=d;d=p.handler;f=p.selector}d.guid||(d.guid=c.guid++);(h=k.events)||(h=k.events={});(g=k.handle)||(g=k.handle=function(b){return"undefined"!==typeof c&&c.event.triggered!==
b.type?c.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(O)||[""];for(k=b.length;k--;){var n=xb.exec(b[k])||[];var q=l=n[1];var v=(n[2]||"").split(".").sort();q&&(n=c.event.special[q]||{},q=(f?n.delegateType:n.bindType)||q,n=c.event.special[q]||{},l=c.extend({type:q,origType:l,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:v.join(".")},p),(m=h[q])||(m=h[q]=[],m.delegateCount=0,n.setup&&!1!==n.setup.call(a,e,v,g)||a.addEventListener&&
a.addEventListener(q,g,!1)),n.add&&(n.add.call(a,l),l.handler.guid||(l.handler.guid=d.guid)),f?m.splice(m.delegateCount++,0,l):m.push(l),c.event.global[q]=!0)}}},remove:function(a,b,d,e,f){var g,h,k,l,m,p=r.hasData(a)&&r.get(a);if(p&&(k=p.events)){b=(b||"").match(O)||[""];for(l=b.length;l--;){var n=xb.exec(b[l])||[];var q=m=n[1];var v=(n[2]||"").split(".").sort();if(q){var t=c.event.special[q]||{};q=(e?t.delegateType:t.bindType)||q;var w=k[q]||[];n=n[2]&&new RegExp("(^|\\.)"+v.join("\\.(?:.*\\.|)")+
"(\\.|$)");for(h=g=w.length;g--;){var x=w[g];!f&&m!==x.origType||d&&d.guid!==x.guid||n&&!n.test(x.namespace)||e&&e!==x.selector&&("**"!==e||!x.selector)||(w.splice(g,1),x.selector&&w.delegateCount--,t.remove&&t.remove.call(a,x))}h&&!w.length&&(t.teardown&&!1!==t.teardown.call(a,v,p.handle)||c.removeEvent(a,q,p.handle),delete k[q])}else for(q in k)c.event.remove(a,q+b[l],d,e,!0)}c.isEmptyObject(k)&&(delete p.handle,r.remove(a,"events"))}},trigger:function(a,b,d,e){var f,g,h=[d||v],k=Qa.call(a,"type")?
a.type:a;var l=Qa.call(a,"namespace")?a.namespace.split("."):[];var m=f=d=d||v;if(3!==d.nodeType&&8!==d.nodeType&&!wb.test(k+c.event.triggered)){0<=k.indexOf(".")&&(l=k.split("."),k=l.shift(),l.sort());var p=0>k.indexOf(":")&&"on"+k;a=a[c.expando]?a:new c.Event(k,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=l.join(".");a.namespace_re=a.namespace?new RegExp("(^|\\.)"+l.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=d);b=null==b?[a]:c.makeArray(b,[a]);l=c.event.special[k]||
{};if(e||!l.trigger||!1!==l.trigger.apply(d,b)){if(!e&&!l.noBubble&&!c.isWindow(d)){var n=l.delegateType||k;wb.test(n+k)||(m=m.parentNode);for(;m;m=m.parentNode)h.push(m),f=m;f===(d.ownerDocument||v)&&h.push(f.defaultView||f.parentWindow||q)}for(f=0;(m=h[f++])&&!a.isPropagationStopped();)a.type=1<f?n:l.bindType||k,(g=(r.get(m,"events")||{})[a.type]&&r.get(m,"handle"))&&g.apply(m,b),(g=p&&m[p])&&g.apply&&c.acceptData(m)&&(a.result=g.apply(m,b),!1===a.result&&a.preventDefault());a.type=k;e||a.isDefaultPrevented()||
l._default&&!1!==l._default.apply(h.pop(),b)||!c.acceptData(d)||!p||!c.isFunction(d[k])||c.isWindow(d)||((f=d[p])&&(d[p]=null),c.event.triggered=k,d[k](),c.event.triggered=void 0,f&&(d[p]=f));return a.result}}},dispatch:function(a){a=c.event.fix(a);var b,d,e,f=N.call(arguments);var g=(r.get(this,"events")||{})[a.type]||[];var h=c.event.special[a.type]||{};f[0]=a;a.delegateTarget=this;if(!h.preDispatch||!1!==h.preDispatch.call(this,a)){var k=c.event.handlers.call(this,a,g);for(g=0;(e=k[g++])&&!a.isPropagationStopped();)for(a.currentTarget=
e.elem,b=0;(d=e.handlers[b++])&&!a.isImmediatePropagationStopped();)if(!a.namespace_re||a.namespace_re.test(d.namespace))a.handleObj=d,a.data=d.data,d=((c.event.special[d.origType]||{}).handle||d.handler).apply(e.elem,f),void 0!==d&&!1===(a.result=d)&&(a.preventDefault(),a.stopPropagation());h.postDispatch&&h.postDispatch.call(this,a);return a.result}},handlers:function(a,b){var d,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&(!a.button||"click"!==a.type))for(;g!==this;g=g.parentNode||this)if(!0!==
g.disabled||"click"!==a.type){var h=[];for(d=0;d<f;d++){var k=b[d];var l=k.selector+" ";void 0===h[l]&&(h[l]=k.needsContext?0<=c(l,this).index(g):c.find(l,this,null,[g]).length);h[l]&&h.push(k)}h.length&&e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,
b){null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode);return a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c=b.button;if(null==a.pageX&&null!=b.clientX){var e=a.target.ownerDocument||v;var f=e.documentElement;e=e.body;a.pageX=b.clientX+(f&&f.scrollLeft||e&&e.scrollLeft||0)-(f&&f.clientLeft||e&&e.clientLeft||0);a.pageY=b.clientY+(f&&f.scrollTop||e&&e.scrollTop||0)-(f&&f.clientTop||e&&e.clientTop||
0)}a.which||void 0===c||(a.which=c&1?1:c&2?3:c&4?2:0);return a}},fix:function(a){if(a[c.expando])return a;var b=a.type;var d=a,e=this.fixHooks[b];e||(this.fixHooks[b]=e=fc.test(b)?this.mouseHooks:ec.test(b)?this.keyHooks:{});var f=e.props?this.props.concat(e.props):this.props;a=new c.Event(d);for(b=f.length;b--;){var g=f[b];a[g]=d[g]}a.target||(a.target=v);3===a.target.nodeType&&(a.target=a.target.parentNode);return e.filter?e.filter(a,d):a},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==
Za()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===Za()&&this.blur)return this.blur(),!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===this.type&&this.click&&c.nodeName(this,"input"))return this.click(),!1},_default:function(a){return c.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:!0,
originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&a.getPreventDefault&&a.getPreventDefault()?da:Y):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||
c.now();this[c.expando]=!0};c.Event.prototype={isDefaultPrevented:Y,isPropagationStopped:Y,isImmediatePropagationStopped:Y,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=da;a&&a.preventDefault&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=da;a&&a.stopPropagation&&a.stopPropagation()},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=da;this.stopPropagation()}};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},
function(a,b){c.event.special[a]={delegateType:b,bindType:b,handle:function(a){var d=a.relatedTarget,f=a.handleObj;if(!d||d!==this&&!c.contains(this,d)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});t.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=function(a){c.event.simulate(b,a.target,c.event.fix(a),!0)};c.event.special[b]={setup:function(){var c=this.ownerDocument||this,f=r.access(c,b);f||c.addEventListener(a,d,!0);r.access(c,b,(f||
0)+1)},teardown:function(){var c=this.ownerDocument||this,f=r.access(c,b)-1;f?r.access(c,b,f):(c.removeEventListener(a,d,!0),r.remove(c,b))}}});c.fn.extend({on:function(a,b,d,e,f){var g;if("object"===typeof a){"string"!==typeof b&&(d=d||b,b=void 0);for(g in a)this.on(g,b,d,a[g],f);return this}null==d&&null==e?(e=b,d=b=void 0):null==e&&("string"===typeof b?(e=d,d=void 0):(e=d,d=b,b=void 0));if(!1===e)e=Y;else if(!e)return this;if(1===f){var h=e;e=function(a){c().off(a);return h.apply(this,arguments)};
e.guid=h.guid||(h.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,c,e){return this.on(a,b,c,e,1)},off:function(a,b,d){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=void 0;!1===d&&(d=Y);return this.each(function(){c.event.remove(this,a,d,b)})},
trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});var yb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,zb=/<([\w:]+)/,gc=/<|&#?\w+;/,hc=/<(?:script|style|link)/i,ic=/checked\s*(?:[^=]|=\s*.checked.)/i,Ab=/^$|\/(?:java|ecma)script/i,Rb=/^true\/(.*)/,jc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,E={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,
"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};E.optgroup=E.option;E.tbody=E.tfoot=E.colgroup=E.caption=E.thead;E.th=E.td;c.extend({clone:function(a,b,d){var e,f=a.cloneNode(!0),g=c.contains(a.ownerDocument,a);if(!(t.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){var h=x(f);var k=x(a);var l=0;for(e=k.length;l<e;l++){var m=k[l],p=h[l],n=p.nodeName.toLowerCase();
if("input"===n&&vb.test(m.type))p.checked=m.checked;else if("input"===n||"textarea"===n)p.defaultValue=m.defaultValue}}if(b)if(d)for(k=k||x(a),h=h||x(f),l=0,e=k.length;l<e;l++)ab(k[l],h[l]);else ab(a,f);h=x(f,"script");0<h.length&&Ka(h,!g&&x(a,"script"));return f},buildFragment:function(a,b,d,e){for(var f,g,h,k=b.createDocumentFragment(),l=[],m=0,p=a.length;m<p;m++)if((f=a[m])||0===f)if("object"===c.type(f))c.merge(l,f.nodeType?[f]:f);else if(gc.test(f)){g=g||k.appendChild(b.createElement("div"));
h=(zb.exec(f)||["",""])[1].toLowerCase();h=E[h]||E._default;g.innerHTML=h[1]+f.replace(yb,"<$1></$2>")+h[2];for(h=h[0];h--;)g=g.lastChild;c.merge(l,g.childNodes);g=k.firstChild;g.textContent=""}else l.push(b.createTextNode(f));k.textContent="";for(m=0;f=l[m++];)if(!e||-1===c.inArray(f,e))if(a=c.contains(f.ownerDocument,f),g=x(k.appendChild(f),"script"),a&&Ka(g),d)for(h=0;f=g[h++];)Ab.test(f.type||"")&&d.push(f);return k},cleanData:function(a){for(var b,d,e,f,g,h,k=c.event.special,l=0;void 0!==(d=
a[l]);l++){if(c.acceptData(d)&&(g=d[r.expando])&&(b=r.cache[g])){e=Object.keys(b.events||{});if(e.length)for(h=0;void 0!==(f=e[h]);h++)k[f]?c.event.remove(d,f):c.removeEvent(d,f,b.handle);r.cache[g]&&delete r.cache[g]}delete w.cache[d[w.expando]]}}});c.fn.extend({text:function(a){return U(this,function(a){return void 0===a?c.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,a,arguments.length)},append:function(){return this.domManip(arguments,
function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||$a(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=$a(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},
remove:function(a,b){for(var d=a?c.filter(a,this):this,e=0;null!=(a=d[e]);e++)b||1!==a.nodeType||c.cleanData(x(a)),a.parentNode&&(b&&c.contains(a.ownerDocument,a)&&Ka(x(a,"script")),a.parentNode.removeChild(a));return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(c.cleanData(x(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return U(this,function(a){var b=this[0]||
{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!hc.test(a)&&!E[(zb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(yb,"<$1></$2>");try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(c.cleanData(x(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=arguments[0];this.domManip(arguments,function(b){a=this.parentNode;c.cleanData(x(this));a&&a.replaceChild(b,this)});return a&&(a.length||a.nodeType)?
this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b){a=sb.apply([],a);var d,e=0,f=this.length,g=this,h=f-1,k=a[0],l=c.isFunction(k);if(l||1<f&&"string"===typeof k&&!t.checkClone&&ic.test(k))return this.each(function(c){var d=g.eq(c);l&&(a[0]=k.call(this,c,d.html()));d.domManip(a,b)});if(f){var m=c.buildFragment(a,this[0].ownerDocument,!1,this);var p=m.firstChild;1===m.childNodes.length&&(m=p);if(p){p=c.map(x(m,"script"),Pb);for(d=p.length;e<f;e++){var n=m;e!==h&&
(n=c.clone(n,!0,!0),d&&c.merge(p,x(n,"script")));b.call(this[e],n,e)}if(d)for(m=p[p.length-1].ownerDocument,c.map(p,Qb),e=0;e<d;e++)n=p[e],Ab.test(n.type||"")&&!r.access(n,"globalEval")&&c.contains(m,n)&&(n.src?c._evalUrl&&c._evalUrl(n.src):c.globalEval(n.textContent.replace(jc,"")))}}return this}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var d=[],f=c(a),g=f.length-1,h=0;h<=g;h++)a=h===
g?this:this.clone(!0),c(f[h])[b](a),Pa.apply(d,a.get());return this.pushStack(d)}});var wa,db={},eb=/^margin/,La=new RegExp("^("+Fa+")(?!px)[a-z%]+$","i"),xa=function(a){return a.ownerDocument.defaultView.getComputedStyle(a,null)};(function(){function a(){g.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%";e.appendChild(f);var a=q.getComputedStyle(g,null);b="1%"!==a.top;
d="4px"===a.width;e.removeChild(f)}var b,d,e=v.documentElement,f=v.createElement("div"),g=v.createElement("div");g.style.backgroundClip="content-box";g.cloneNode(!0).style.backgroundClip="";t.clearCloneStyle="content-box"===g.style.backgroundClip;f.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px";f.appendChild(g);q.getComputedStyle&&c.extend(t,{pixelPosition:function(){a();return b},boxSizingReliable:function(){null==d&&a();return d},reliableMarginRight:function(){var a=
g.appendChild(v.createElement("div"));a.style.cssText=g.style.cssText="padding:0;margin:0;border:0;display:block;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box";a.style.marginRight=a.style.width="0";g.style.width="1px";e.appendChild(f);a=!parseFloat(q.getComputedStyle(a,null).marginRight);e.removeChild(f);g.innerHTML="";return a}})})();c.swap=function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c};
var kc=/^(none|table(?!-c[ea]).+)/,Sb=new RegExp("^("+Fa+")(.*)$","i"),lc=new RegExp("^([+-])=("+Fa+")","i"),mc={position:"absolute",visibility:"hidden",display:"block"},Bb={letterSpacing:0,fontWeight:400},hb=["Webkit","O","Moz","ms"];c.extend({cssHooks:{opacity:{get:function(a,b){if(b)return a=ma(a,"opacity"),""===a?"1":a}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,
b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g=c.camelCase(b),h=a.style;b=c.cssProps[g]||(c.cssProps[g]=gb(h,g));var k=c.cssHooks[b]||c.cssHooks[g];if(void 0!==d){var l=typeof d;"string"===l&&(f=lc.exec(d))&&(d=(f[1]+1)*f[2]+parseFloat(c.css(a,b)),l="number");null!=d&&d===d&&("number"!==l||c.cssNumber[g]||(d+="px"),t.clearCloneStyle||""!==d||0!==b.indexOf("background")||(h[b]="inherit"),k&&"set"in k&&void 0===(d=k.set(a,d,e))||(h[b]="",h[b]=d))}else return k&&"get"in k&&void 0!==(f=
k.get(a,!1,e))?f:h[b]}},css:function(a,b,d,e){var f;var g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=gb(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));void 0===f&&(f=ma(a,b,e));"normal"===f&&b in Bb&&(f=Bb[b]);return""===d||d?(a=parseFloat(f),!0===d||c.isNumeric(a)?a||0:f):f}});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return 0===a.offsetWidth&&kc.test(c.css(a,"display"))?c.swap(a,mc,function(){return kb(a,b,f)}):kb(a,b,f)},set:function(a,
e,f){var d=f&&xa(a);return ib(a,e,f?jb(a,b,f,"border-box"===c.css(a,"boxSizing",!1,d),d):0)}}});c.cssHooks.marginRight=fb(t.reliableMarginRight,function(a,b){if(b)return c.swap(a,{display:"inline-block"},ma,[a,"marginRight"])});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+Z[d]+b]=c[d]||c[d-2]||c[0];return f}};eb.test(a)||(c.cssHooks[a+b].set=ib)});c.fn.extend({css:function(a,b){return U(this,
function(a,b,f){var d,e={},k=0;if(c.isArray(b)){f=xa(a);for(d=b.length;k<d;k++)e[b[k]]=c.css(a,b[k],!1,f);return e}return void 0!==f?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)},show:function(){return lb(this,!0)},hide:function(){return lb(this)},toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){na(this)?c(this).show():c(this).hide()})}});c.Tween=C;C.prototype={constructor:C,init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||"swing";
this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=C.propHooks[this.prop];return a&&a.get?a.get(this):C.propHooks._default.get(this)},run:function(a){var b,d=C.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):C.propHooks._default.set(this);
return this}};C.prototype.init.prototype=C.prototype;C.propHooks={_default:{get:function(a){return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(a=c.css(a.elem,a.prop,""))&&"auto"!==a?a:0:a.elem[a.prop]},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else a.elem.style&&(null!=a.elem.style[c.cssProps[a.prop]]||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};C.propHooks.scrollTop=C.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&
(a.elem[a.prop]=a.now)}};c.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2}};c.fx=C.prototype.init;c.fx.step={};var aa,Ga,nc=/^(?:toggle|show|hide)$/,Cb=new RegExp("^(?:([+-])=|)("+Fa+")([a-z%]*)$","i"),oc=/queueHooks$/,pa=[function(a,b,d){var e,f=this,g={},h=a.style,k=a.nodeType&&na(a),l=r.get(a,"fxshow");if(!d.queue){var m=c._queueHooks(a,"fx");if(null==m.unqueued){m.unqueued=0;var p=m.empty.fire;m.empty.fire=function(){m.unqueued||p()}}m.unqueued++;f.always(function(){f.always(function(){m.unqueued--;
c.queue(a,"fx").length||m.empty.fire()})})}if(1===a.nodeType&&("height"in b||"width"in b)){d.overflow=[h.overflow,h.overflowX,h.overflowY];var n=c.css(a,"display");"none"===n&&(n=cb(a.nodeName));"inline"===n&&"none"===c.css(a,"float")&&(h.display="inline-block")}d.overflow&&(h.overflow="hidden",f.always(function(){h.overflow=d.overflow[0];h.overflowX=d.overflow[1];h.overflowY=d.overflow[2]}));for(e in b)if(n=b[e],nc.exec(n)){delete b[e];var q=q||"toggle"===n;if(n===(k?"hide":"show"))if("show"===n&&
l&&void 0!==l[e])k=!0;else continue;g[e]=l&&l[e]||c.style(a,e)}if(!c.isEmptyObject(g))for(e in l?"hidden"in l&&(k=l.hidden):l=r.access(a,"fxshow",{}),q&&(l.hidden=!k),k?c(a).show():f.done(function(){c(a).hide()}),f.done(function(){var b;r.remove(a,"fxshow");for(b in g)c.style(a,b,g[b])}),g)b=nb(k?l[e]:0,e,f),e in l||(l[e]=b.start,k&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],oa={"*":[function(a,b){var d=this.createTween(a,b),e=d.cur(),f=(b=Cb.exec(b))&&b[3]||(c.cssNumber[a]?"":"px"),
g=(c.cssNumber[a]||"px"!==f&&+e)&&Cb.exec(c.css(d.elem,a)),h=1,k=20;if(g&&g[3]!==f){f=f||g[3];b=b||[];g=+e||1;do h=h||".5",g/=h,c.style(d.elem,a,g+f);while(h!==(h=d.cur()/e)&&1!==h&&--k)}b&&(g=d.start=+g||+e||0,d.unit=f,d.end=b[1]?g+(b[1]+1)*b[2]:+b[2]);return d}]};c.Animation=c.extend(ob,{tweener:function(a,b){c.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++)d=a[e],oa[d]=oa[d]||[],oa[d].unshift(b)},prefilter:function(a,b){b?pa.unshift(a):pa.push(a)}});c.speed=function(a,
b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:"number"===typeof e.duration?e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(na).css("opacity",
0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e);b=function(){var b=ob(this,c.extend({},a),g);(f||r.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};"string"!==typeof a&&(d=b,b=a,a=void 0);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,k=r.get(this);if(g)k[g]&&
k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&oc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=r.get(this),d=b[a+"queue"];var e=b[a+"queueHooks"];var f=c.timers,g=d?d.length:0;b.finish=!0;c.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,
1));for(e=0;e<g;e++)d[e]&&d[e].finish&&d[e].finish.call(this);delete b.finish})}});c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"===typeof a?d.apply(this,arguments):this.animate(ea(b,!0),a,c,g)}});c.each({slideDown:ea("show"),slideUp:ea("hide"),slideToggle:ea("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.timers=[];c.fx.tick=
function(){var a=0,b=c.timers;for(aa=c.now();a<b.length;a++){var d=b[a];d()||b[a]!==d||b.splice(a--,1)}b.length||c.fx.stop();aa=void 0};c.fx.timer=function(a){c.timers.push(a);a()?c.fx.start():c.timers.pop()};c.fx.interval=13;c.fx.start=function(){Ga||(Ga=setInterval(c.fx.tick,c.fx.interval))};c.fx.stop=function(){clearInterval(Ga);Ga=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fn.delay=function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,c){var d=setTimeout(b,a);
c.stop=function(){clearTimeout(d)}})};(function(){var a=v.createElement("input"),b=v.createElement("select"),c=b.appendChild(v.createElement("option"));a.type="checkbox";t.checkOn=""!==a.value;t.optSelected=c.selected;b.disabled=!0;t.optDisabled=!c.disabled;a=v.createElement("input");a.value="t";a.type="radio";t.radioValue="t"===a.value})();var V=c.expr.attrHandle;c.fn.extend({attr:function(a,b){return U(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,
a)})}});c.extend({attr:function(a,b,d){var e,f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);if(1!==f||!c.isXMLDoc(a)){b=b.toLowerCase();var g=c.attrHooks[b]||(c.expr.match.bool.test(b)?pc:void 0)}if(void 0!==d)if(null===d)c.removeAttr(a,b);else{if(g&&"set"in g&&void 0!==(e=g.set(a,d,b)))return e;a.setAttribute(b,d+"");return d}else{if(g&&"get"in g&&null!==(e=g.get(a,b)))return e;e=c.find.attr(a,b);return null==e?void 0:e}}},removeAttr:function(a,
b){var d=0,e=b&&b.match(O);if(e&&1===a.nodeType)for(;b=e[d++];){var f=c.propFix[b]||b;c.expr.match.bool.test(b)&&(a[f]=!1);a.removeAttribute(b)}},attrHooks:{type:{set:function(a,b){if(!t.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}}}});var pc={set:function(a,b,d){!1===b?c.removeAttr(a,d):a.setAttribute(d,d);return d}};c.each(c.expr.match.bool.source.match(/\w+/g),function(a,b){var d=V[b]||c.find.attr;V[b]=function(a,b,c){if(!c){var e=
V[b];V[b]=f;var f=null!=d(a,b,c)?b.toLowerCase():null;V[b]=e}return f}});var qc=/^(?:input|select|textarea|button)$/i;c.fn.extend({prop:function(a,b){return U(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[c.propFix[a]||a]})}});c.extend({propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,d){var e,f=a.nodeType;if(a&&3!==f&&8!==f&&2!==f){if(1!==f||!c.isXMLDoc(a)){b=c.propFix[b]||b;var g=c.propHooks[b]}return void 0!==d?g&&"set"in g&&
void 0!==(e=g.set(a,d,b))?e:a[b]=d:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){return a.hasAttribute("tabindex")||qc.test(a.nodeName)||a.href?a.tabIndex:-1}}}});t.optSelected||(c.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null}});c.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){c.propFix[this.toLowerCase()]=this});var Sa=
/[\t\r\n\f]/g;c.fn.extend({addClass:function(a){var b,d,e;var f="string"===typeof a&&a;var g=0,h=this.length;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(f)for(f=(a||"").match(O)||[];g<h;g++){var k=this[g];if(b=1===k.nodeType&&(k.className?(" "+k.className+" ").replace(Sa," "):" ")){for(e=0;d=f[e++];)0>b.indexOf(" "+d+" ")&&(b+=d+" ");b=c.trim(b);k.className!==b&&(k.className=b)}}return this},removeClass:function(a){var b,d,e;var f=0===arguments.length||
"string"===typeof a&&a;var g=0,h=this.length;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(f)for(f=(a||"").match(O)||[];g<h;g++){var k=this[g];if(b=1===k.nodeType&&(k.className?(" "+k.className+" ").replace(Sa," "):"")){for(e=0;d=f[e++];)for(;0<=b.indexOf(" "+d+" ");)b=b.replace(" "+d+" "," ");b=a?c.trim(b):"";k.className!==b&&(k.className=b)}}return this},toggleClass:function(a,b){var d=typeof a;return"boolean"===typeof b&&"string"===d?b?
this.addClass(a):this.removeClass(a):c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,this.className,b),b)}):this.each(function(){if("string"===d)for(var b,f=0,g=c(this),h=a.match(O)||[];b=h[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else if("undefined"===d||"boolean"===d)this.className&&r.set(this,"__className__",this.className),this.className=this.className||!1===a?"":r.get(this,"__className__")||""})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;b<c;b++)if(1===
this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Sa," ").indexOf(a))return!0;return!1}});var rc=/\r/g;c.fn.extend({val:function(a){var b,d,e=this[0];if(arguments.length){var f=c.isFunction(a);return this.each(function(d){1===this.nodeType&&(d=f?a.call(this,d,c(this).val()):a,null==d?d="":"number"===typeof d?d+="":c.isArray(d)&&(d=c.map(d,function(a){return null==a?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,d,"value")||(this.value=
d))})}if(e){if((b=c.valHooks[e.type]||c.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(d=b.get(e,"value")))return d;d=e.value;return"string"===typeof d?d.replace(rc,""):null==d?"":d}}});c.extend({valHooks:{select:{get:function(a){for(var b,d=a.options,e=a.selectedIndex,f=(a="select-one"===a.type||0>e)?null:[],g=a?e+1:d.length,h=0>e?g:a?e:0;h<g;h++)if(b=d[h],!(!b.selected&&h!==e||(t.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&c.nodeName(b.parentNode,
"optgroup"))){b=c(b).val();if(a)return b;f.push(b)}return f},set:function(a,b){for(var d,e=a.options,f=c.makeArray(b),g=e.length;g--;)if(b=e[g],b.selected=0<=c.inArray(c(b).val(),f))d=!0;d||(a.selectedIndex=-1);return f}}}});c.each(["radio","checkbox"],function(){c.valHooks[this]={set:function(a,b){if(c.isArray(b))return a.checked=0<=c.inArray(c(a).val(),b)}};t.checkOn||(c.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,e){return this.on(b,a,c,e)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var Ta=c.now(),Ua=/\?/;c.parseJSON=function(a){return JSON.parse(a+"")};c.parseXML=
function(a){if(!a||"string"!==typeof a)return null;try{var b=new DOMParser;var d=b.parseFromString(a,"text/xml")}catch(e){d=void 0}d&&!d.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return d};var sc=/#.*$/,Db=/([?&])_=[^&]*/,tc=/^(.*?):[ \t]*([^\r\n]*)$/mg,uc=/^(?:GET|HEAD)$/,vc=/^\/\//,Eb=/^([\w.+-]+:)(?:\/\/(?:[^\/?#]*@|)([^\/?#:]*)(?::(\d+)|)|)/,Fb={},Ma={},Gb="*/".concat("*");try{var W=location.href}catch(a){W=v.createElement("a"),W.href="",W=W.href}var ka=Eb.exec(W.toLowerCase())||
[];c.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:W,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(ka[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Gb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,
"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Na(Na(a,c.ajaxSettings),b):Na(c.ajaxSettings,a)},ajaxPrefilter:pb(Fb),ajaxTransport:pb(Ma),ajax:function(a,b){function d(a,b,d,g){var l=b;if(2!==x){x=2;h&&clearTimeout(h);e=void 0;f=g||"";A.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(d){var t=m;for(var w=A,G,M,C,y,I=t.contents,K=t.dataTypes;"*"===K[0];)K.shift(),void 0===G&&(G=t.mimeType||w.getResponseHeader("Content-Type"));
if(G)for(M in I)if(I[M]&&I[M].test(G)){K.unshift(M);break}if(K[0]in d)C=K[0];else{for(M in d){if(!K[0]||t.converters[M+" "+K[0]]){C=M;break}y||(y=M)}C=C||y}C?(C!==K[0]&&K.unshift(C),t=d[C]):t=void 0}a:{d=m;G=t;M=A;C=g;var J;w={};I=d.dataTypes.slice();if(I[1])for(P in d.converters)w[P.toLowerCase()]=d.converters[P];for(y=I.shift();y;){d.responseFields[y]&&(M[d.responseFields[y]]=G);!E&&C&&d.dataFilter&&(G=d.dataFilter(G,d.dataType));var E=y;if(y=I.shift())if("*"===y)y=E;else if("*"!==E&&E!==y){var P=
w[E+" "+y]||w["* "+y];if(!P)for(J in w)if(t=J.split(" "),t[1]===y&&(P=w[E+" "+t[0]]||w["* "+t[0]])){!0===P?P=w[J]:!0!==w[J]&&(y=t[0],I.unshift(t[1]));break}if(!0!==P)if(P&&d["throws"])G=P(G);else try{G=P(G)}catch(ac){t={state:"parsererror",error:P?ac:"No conversion from "+E+" to "+y};break a}}}t={state:"success",data:G}}if(g)if(m.ifModified&&((l=A.getResponseHeader("Last-Modified"))&&(c.lastModified[L]=l),(l=A.getResponseHeader("etag"))&&(c.etag[L]=l)),204===a||"HEAD"===m.type)l="nocontent";else if(304===
a)l="notmodified";else{l=t.state;var O=t.data;var N=t.error;g=!N}else if(N=l,a||!l)l="error",0>a&&(a=0);A.status=a;A.statusText=(b||l)+"";g?q.resolveWith(p,[O,l,A]):q.rejectWith(p,[A,l,N]);A.statusCode(v);v=void 0;k&&n.trigger(g?"ajaxSuccess":"ajaxError",[A,m,g?O:N]);r.fireWith(p,[A,l]);k&&(n.trigger("ajaxComplete",[A,m]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,k,l,m=c.ajaxSetup({},b),p=m.context||m,n=m.context&&(p.nodeType||p.jquery)?c(p):
c.event,q=c.Deferred(),r=c.Callbacks("once memory"),v=m.statusCode||{},t={},w={},x=0,C="canceled",A={readyState:0,getResponseHeader:function(a){var b;if(2===x){if(!g)for(g={};b=tc.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return 2===x?f:null},setRequestHeader:function(a,b){var c=a.toLowerCase();x||(a=w[c]=w[c]||a,t[a]=b);return this},overrideMimeType:function(a){x||(m.mimeType=a);return this},statusCode:function(a){var b;if(a)if(2>
x)for(b in a)v[b]=[v[b],a[b]];else A.always(a[A.status]);return this},abort:function(a){a=a||C;e&&e.abort(a);d(0,a);return this}};q.promise(A).complete=r.add;A.success=A.done;A.error=A.fail;m.url=((a||m.url||W)+"").replace(sc,"").replace(vc,ka[1]+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=c.trim(m.dataType||"*").toLowerCase().match(O)||[""];null==m.crossDomain&&(a=Eb.exec(m.url.toLowerCase()),m.crossDomain=!(!a||a[1]===ka[1]&&a[2]===ka[2]&&(a[3]||("http:"===a[1]?"80":"443"))===(ka[3]||
("http:"===ka[1]?"80":"443"))));m.data&&m.processData&&"string"!==typeof m.data&&(m.data=c.param(m.data,m.traditional));qb(Fb,m,b,A);if(2===x)return A;(k=m.global)&&0===c.active++&&c.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!uc.test(m.type);var L=m.url;m.hasContent||(m.data&&(L=m.url+=(Ua.test(L)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=Db.test(L)?L.replace(Db,"$1_="+Ta++):L+(Ua.test(L)?"&":"?")+"_="+Ta++));m.ifModified&&(c.lastModified[L]&&A.setRequestHeader("If-Modified-Since",
c.lastModified[L]),c.etag[L]&&A.setRequestHeader("If-None-Match",c.etag[L]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&A.setRequestHeader("Content-Type",m.contentType);A.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Gb+"; q=0.01":""):m.accepts["*"]);for(l in m.headers)A.setRequestHeader(l,m.headers[l]);if(m.beforeSend&&(!1===m.beforeSend.call(p,A,m)||2===x))return A.abort();C="abort";for(l in{success:1,error:1,
complete:1})A[l](m[l]);if(e=qb(Ma,m,b,A)){A.readyState=1;k&&n.trigger("ajaxSend",[A,m]);m.async&&0<m.timeout&&(h=setTimeout(function(){A.abort("timeout")},m.timeout));try{x=1,e.send(t,d)}catch(G){if(2>x)d(-1,G);else throw G;}}else d(-1,"No Transport");return A},getJSON:function(a,b,d){return c.get(a,b,d,"json")},getScript:function(a,b){return c.get(a,void 0,b,"script")}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){c.isFunction(e)&&(g=g||f,f=e,e=void 0);return c.ajax({url:a,type:b,
dataType:g,data:e,success:f})}});c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c._evalUrl=function(a){return c.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,"throws":!0})};c.fn.extend({wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(!0);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=
this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()}});
c.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight};c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)};var wc=/%20/g,Ub=/\[\]$/,Hb=/\r?\n/g,xc=/^(?:submit|button|image|reset|file)$/i,yc=/^(?:input|select|textarea|keygen)/i;c.param=function(a,b){var d,e=[],f=function(a,b){b=c.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};void 0===b&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,
function(){f(this.name,this.value)});else for(d in a)Oa(d,a[d],b,f);return e.join("&").replace(wc,"+")};c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&yc.test(this.nodeName)&&!xc.test(a)&&(this.checked||!vb.test(a))}).map(function(a,b){a=c(this).val();return null==a?null:c.isArray(a)?
c.map(a,function(a){return{name:b.name,value:a.replace(Hb,"\r\n")}}):{name:b.name,value:a.replace(Hb,"\r\n")}}).get()}});c.ajaxSettings.xhr=function(){try{return new XMLHttpRequest}catch(a){}};var zc=0,Ha={},Ac={0:200,1223:204},ta=c.ajaxSettings.xhr();if(q.ActiveXObject)c(q).on("unload",function(){for(var a in Ha)Ha[a]()});t.cors=!!ta&&"withCredentials"in ta;t.ajax=ta=!!ta;c.ajaxTransport(function(a){var b;if(t.cors||ta&&!a.crossDomain)return{send:function(c,e){var d,g=a.xhr(),h=++zc;g.open(a.type,
a.url,a.async,a.username,a.password);if(a.xhrFields)for(d in a.xhrFields)g[d]=a.xhrFields[d];a.mimeType&&g.overrideMimeType&&g.overrideMimeType(a.mimeType);a.crossDomain||c["X-Requested-With"]||(c["X-Requested-With"]="XMLHttpRequest");for(d in c)g.setRequestHeader(d,c[d]);b=function(a){return function(){b&&(delete Ha[h],b=g.onload=g.onerror=null,"abort"===a?g.abort():"error"===a?e(g.status,g.statusText):e(Ac[g.status]||g.status,g.statusText,"string"===typeof g.responseText?{text:g.responseText}:void 0,
g.getAllResponseHeaders()))}};g.onload=b();g.onerror=b("error");b=Ha[h]=b("abort");g.send(a.hasContent&&a.data||null)},abort:function(){b&&b()}}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});c.ajaxTransport("script",
function(a){if(a.crossDomain){var b,d;return{send:function(e,f){b=c("<script>").prop({async:!0,charset:a.scriptCharset,src:a.url}).on("load error",d=function(a){b.remove();d=null;a&&f("error"===a.type?404:200,a.type)});v.head.appendChild(b[0])},abort:function(){d&&d()}}}});var Ib=[],Va=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Ib.pop()||c.expando+"_"+Ta++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f=!1!==a.jsonp&&(Va.test(a.url)?
"url":"string"===typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Va.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(Va,"$1"+g):!1!==a.jsonp&&(a.url+=(Ua.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||c.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=q[g];q[g]=function(){e=arguments};d.always(function(){q[g]=
h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Ib.push(g));e&&c.isFunction(h)&&h(e[0]);e=h=void 0});return"script"}});c.parseHTML=function(a,b,d){if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(d=b,b=!1);b=b||v;var e=ub.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=c.buildFragment([a],b,d);d&&d.length&&c(d).remove();return c.merge([],e.childNodes)};var Jb=c.fn.load;c.fn.load=function(a,b,d){if("string"!==typeof a&&Jb)return Jb.apply(this,arguments);var e,f,g=this,h=a.indexOf(" ");
if(0<=h){var k=a.slice(h);a=a.slice(0,h)}c.isFunction(b)?(d=b,b=void 0):b&&"object"===typeof b&&(e="POST");0<g.length&&c.ajax({url:a,type:e,dataType:"html",data:b}).done(function(a){f=arguments;g.html(k?c("<div>").append(c.parseHTML(a)).find(k):a)}).complete(d&&function(a,b){g.each(d,f||[a.responseText,b,a])});return this};c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};var Kb=q.document.documentElement;c.offset={setOffset:function(a,b,d){var e=c.css(a,
"position"),f=c(a),g={};"static"===e&&(a.style.position="relative");var h=f.offset();var k=c.css(a,"top");var l=c.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(k+l).indexOf("auto")?(l=f.position(),k=l.top,l=l.left):(k=parseFloat(k)||0,l=parseFloat(l)||0);c.isFunction(b)&&(b=b.call(a,d,h));null!=b.top&&(g.top=b.top-h.top+k);null!=b.left&&(g.left=b.left-h.left+l);"using"in b?b.using.call(a,g):f.css(g)}};c.fn.extend({offset:function(a){if(arguments.length)return void 0===a?this:this.each(function(b){c.offset.setOffset(this,
a,b)});var b=this[0];var d={top:0,left:0},e=b&&b.ownerDocument;if(e){var f=e.documentElement;if(!c.contains(f,b))return d;"undefined"!==typeof b.getBoundingClientRect&&(d=b.getBoundingClientRect());b=rb(e);return{top:d.top+b.pageYOffset-f.clientTop,left:d.left+b.pageXOffset-f.clientLeft}}},position:function(){if(this[0]){var a=this[0],b={top:0,left:0};if("fixed"===c.css(a,"position"))var d=a.getBoundingClientRect();else{var e=this.offsetParent();d=this.offset();c.nodeName(e[0],"html")||(b=e.offset());
b.top+=c.css(e[0],"borderTopWidth",!0);b.left+=c.css(e[0],"borderLeftWidth",!0)}return{top:d.top-b.top-c.css(a,"marginTop",!0),left:d.left-b.left-c.css(a,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||Kb;a&&!c.nodeName(a,"html")&&"static"===c.css(a,"position");)a=a.offsetParent;return a||Kb})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d="pageYOffset"===b;c.fn[a]=function(c){return U(this,function(a,c,e){var f=
rb(a);if(void 0===e)return f?f[b]:a[c];f?f.scrollTo(d?q.pageXOffset:e,d?e:q.pageYOffset):a[c]=e},a,c,arguments.length,null)}});c.each(["top","left"],function(a,b){c.cssHooks[b]=fb(t.pixelPosition,function(a,e){if(e)return e=ma(a,b),La.test(e)?c(a).position()[b]+"px":e})});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(e,g){var f=arguments.length&&(d||"boolean"!==typeof e),k=d||(!0===e||!0===g?"margin":"border");
return U(this,function(b,d,e){return c.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(d=b.documentElement,Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])):void 0===e?c.css(b,d,k):c.style(b,d,e,k)},b,f?e:void 0,f,null)}})});c.fn.size=function(){return this.length};c.fn.andSelf=c.fn.addBack;"function"===typeof define&&define.amd&&define("jquery",[],function(){return c});var Bc=q.jQuery,Cc=q.$;c.noConflict=function(a){q.$===c&&(q.$=Cc);a&&
q.jQuery===c&&(q.jQuery=Bc);return c};"undefined"===typeof la&&(q.jQuery=q.$=c);return c});
